version: "3.9"
services:
  php-ecma-intl-ext:
    build:
      context: "./resources/docker"
      args:
        icuVersion: "70.1"
        phpVersion: "8.2.8"
    image: "php-ecma-intl-ext:latest"
    container_name: "php-ecma-intl-ext"
    restart: "no"
    volumes:
      - type: "bind"
        source: "./"
        target: "/ext"
    tty: true
    working_dir: "/ext"
    environment:
      - LANG=en_US.utf-8
